version: "3"

services:
  rtbctf:
    build: .
    container_name: rtb_gunicorn
    restart: unless-stopped
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  postgres:
    image: library/postgres:12.1-alpine
    container_name: rtb_postgres
    restart: unless-stopped
    expose:
      - "5432"
    env_file:
      - .env_postgres

  redis:
    image: redis:alpine3.12
    container_name: rtb_redis
    restart: unless-stopped
    expose:
      - "6379"
  
  nginx:
    image: library/nginx:1.16.1-alpine
    container_name: rtb_nginx
    restart: unless-stopped
    hostname: nginx
    volumes:
      - ./rtb_nginx_http:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - rtbctf
